name: ContraNovo
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_0
  - pip=23.2.1=py39h06a4308_0
  - python=3.9.17=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - arrow==1.2.3
      - async-timeout==4.0.2
      - attrs==23.1.0
      - boto3==1.28.33
      - botocore==1.31.33
      - bravado==11.0.3
      - bravado-core==6.1.0
      - cachetools==5.3.1
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - click==8.1.6
      - contourpy==1.1.0
      - cryptography==41.0.3
      - cycler==0.11.0
      - deprecated==1.2.14
      - einops==0.6.1
      - fastobo==0.12.2
      - filelock==3.13.1
      - fonttools==4.42.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.32
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.56.2
      - h5py==3.9.0
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - isoduration==20.11.0
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.3.1
      - jsonpointer==2.4
      - jsonref==1.1.0
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - kiwisolver==1.4.4
      - lark==1.1.7
      - lightning-utilities==0.9.0
      - llvmlite==0.40.1
      - lmdb==1.4.1
      - lxml==4.9.3
      - markdown==3.4.4
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - monotonic==1.6
      - mpmath==1.3.0
      - msgpack==1.0.5
      - multidict==6.0.4
      - natsort==8.4.0
      - neptune==1.6.1
      - networkx==3.2.1
      - numba==0.57.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - packaging==23.1
      - pandas==2.0.3
      - pillow==10.0.0
      - protobuf==4.23.4
      - psutil==5.9.5
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pygithub==2.1.1
      - pyjwt==2.8.0
      - pynacl==1.5.0
      - pyparsing==3.0.9
      - pyteomics==4.6
      - python-dateutil==2.8.2
      - pytorch-lightning==1.9.5
      - pytz==2023.3
      - pyyaml==6.0.1
      - referencing==0.30.2
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3987==1.3.8
      - rpds-py==0.9.2
      - rsa==4.9
      - s3transfer==0.6.2
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - simplejson==3.19.1
      - six==1.16.0
      - smmap==5.0.0
      - spectrum-utils==0.4.2
      - swagger-spec-validator==3.0.3
      - sympy==1.12
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - threadpoolctl==3.2.0
      - tqdm==4.65.1
      - triton==2.1.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==1.26.16
      - webcolors==1.13
      - websocket-client==1.6.2
      - werkzeug==2.3.6
      - wrapt==1.15.0
      - yarl==1.9.2
      - zipp==3.16.2
